name: aapkaparking
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  
  firebase_auth: ^5.1.3
  pinput: ^5.0.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1

  lottie: ^3.1.2
  image_picker: ^1.1.2

  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.3.1
  qr_flutter: ^4.1.0
  cached_network_image: 3.3.1
  intl: ^0.19.0
  mobile_scanner: ^5.1.1
  esc_pos_utils: ^1.1.0
  flutter_blue_plus: ^1.32.12
  blue_thermal_printer: ^1.2.3
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  auto_size_text: ^3.0.0
  pdf: ^3.10.1
  permission_handler: ^11.3.1
  carousel_slider: ^5.0.0
  printing: ^5.13.3
  motion_toast: ^2.11.0
  url_launcher: ^6.3.1
  share_plus: ^10.0.3
  

dependency_overrides:
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/aapka logo.webp"
