// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhMAUczG9KjQZnQsydVuWwvcubCEPzJs8',
    appId: '1:158557455704:android:51dcc9c868afd6830a912d',
    messagingSenderId: '158557455704',
    projectId: 'aapka-parking-2',
    storageBucket: 'aapka-parking-2.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu4Wcj5trTMA61QTnsNw1RhVz00Te3XQ4',
    appId: '1:158557455704:web:1a98402b23927fb70a912d',
    messagingSenderId: '158557455704',
    projectId: 'aapka-parking-2',
    authDomain: 'aapka-parking-2.firebaseapp.com',
    storageBucket: 'aapka-parking-2.appspot.com',
    measurementId: 'G-8HVBZJ8KBM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5cG73mXAivqnwLC5ndJMhka0auy2pMmk',
    appId: '1:158557455704:ios:091f7d920610ba110a912d',
    messagingSenderId: '158557455704',
    projectId: 'aapka-parking-2',
    storageBucket: 'aapka-parking-2.appspot.com',
    iosBundleId: 'com.example.aapkaparking',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5cG73mXAivqnwLC5ndJMhka0auy2pMmk',
    appId: '1:158557455704:ios:091f7d920610ba110a912d',
    messagingSenderId: '158557455704',
    projectId: 'aapka-parking-2',
    storageBucket: 'aapka-parking-2.appspot.com',
    iosBundleId: 'com.example.aapkaparking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu4Wcj5trTMA61QTnsNw1RhVz00Te3XQ4',
    appId: '1:158557455704:web:7b89ea94561cf1ea0a912d',
    messagingSenderId: '158557455704',
    projectId: 'aapka-parking-2',
    authDomain: 'aapka-parking-2.firebaseapp.com',
    storageBucket: 'aapka-parking-2.appspot.com',
    measurementId: 'G-RCYMKW1TQV',
  );

}